function Hd = fdatool-param-script
%FDATOOL-PARAM-SCRIPT Returns a discrete-time filter object.

% Equiripple FIR Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass = 9600;            % Passband Frequency
Fstop = 12000;           % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 16;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 16, ...
    'CoeffAutoScale', true, ...
    'Signed',         true, ...
    'InputWordLength', 16, ...
    'inputFracLength', 15, ...
    'FilterInternals',  'SpecifyPrecision', ...
    'OutputWordLength',  16, ...
    'OutputFracLength',  31, ...
    'ProductWordLength', 31, ...
    'ProductFracLength', 31, ...
    'AccumWordLength',   40, ...
    'AccumFracLength',   31, ...
    'RoundMode',         'floor', ...
    'OverflowMode',      'Saturate');
denormalize(Hd);


% [EOF]
